### ISSUE TITLE
Workflow files become invalid when we re-containerize a cell

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#1112]
Each time we re-containerize a cell it gets a new ID which causes the cell ID saved on the workflow file to be invalid as it does not exist anymore 

```[tasklist]
### Tasks
- [ ] https://github.com/QCDIS/NaaVRE/pull/1257
- [ ] Document this behaviour
```

**Comment by skoulouzis** [comment]
We can try and maintain the ID.
https://github.com/QCDIS/NaaVRE/blob/main/jupyterlab_vre/component_containerizer/handlers.py#L371 
We delete and re-create. We should update

**Comment by gpelouze** [comment]
Cells are now updated instead of deleted and recreated. That probably solves the issue.

→ Check whether it does solve the issue.

**Comment by gpelouze** [comment]
It does not, because we generate a new cell ID each we extract a cell ([`ExtractorHandler.post`](https://github.com/QCDIS/NaaVRE/blob/362541f18c50efc1c1d2511f8b878b37ad5e33dc/jupyterlab_vre/component_containerizer/handlers.py#L180)). As a result, ([`Catalog.get_cell_from_og_node_id(current_cell.node_id)` in `CellsHandler.post`](https://github.com/QCDIS/NaaVRE/blob/362541f18c50efc1c1d2511f8b878b37ad5e33dc/jupyterlab_vre/component_containerizer/handlers.py#L432) always returns `None`.

We should find another way to maintain the ID.
