### ISSUE TITLE
In we still use the 'REGISTRY_URL' variable

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#1115]
In https://github.com/QCDIS/NaaVRE/blob/main/docker/repo_utils/conf_vl_repos.py#L85 we use REGISTRY_URL

**Comment by skoulouzis** [comment]
In https://github.com/QCDIS/NaaVRE/blob/main/.github/workflows/make.yml#L39 we also use 'REGISTRY_URL'. 
The variable is not present in Action variables

**Comment by skoulouzis** [comment]
https://github.com/search?q=repo%3AQCDIS%2FNaaVRE%20REGISTRY_URL&type=code

**Comment by gpelouze** [comment]
`REGISTRY_URL` is still supported, and should be set when the registry does not match the git repository.

- In [conf_vl_repos.py](https://github.com/QCDIS/NaaVRE/blob/8de4a48829cf0807fdcd1c0f89230afab358cc67/docker/repo_utils/conf_vl_repos.py#L53), we handle both cases, where `REGISTRY_URL` is set and not set.
- The CI tests also work but with a caveat: when `REGISTRY_URL` is not set in the repo, [make.yml](https://github.com/QCDIS/NaaVRE/blob/8de4a48829cf0807fdcd1c0f89230afab358cc67/.github/workflows/make.yml#L39) calls [test-build wheel.yml](https://github.com/QCDIS/NaaVRE/blob/8de4a48829cf0807fdcd1c0f89230afab358cc67/.github/workflows/test-build%20wheel.yml#L38) with `REGISTRY_URL=""`. This means that [test_evn_vars.py](https://github.com/QCDIS/NaaVRE/blob/8de4a48829cf0807fdcd1c0f89230afab358cc67/jupyterlab_vre/tests/test_env_vars.py#L13) passes, because it uses `assertIsNotNone`. However, [conf_vl_repos.py](https://github.com/QCDIS/NaaVRE/blob/8de4a48829cf0807fdcd1c0f89230afab358cc67/docker/repo_utils/conf_vl_repos.py#L53) goes into the right if branch because it uses `if REGISTRY_URL`. The `REGISTRY_URL` test should be removed. 

The following files can be updated to provide defaults without `REGISTRY_URL`:
- https://github.com/QCDIS/NaaVRE/blob/8de4a48829cf0807fdcd1c0f89230afab358cc67/docker/export_VARS#L10
- https://github.com/QCDIS/NaaVRE/blob/8de4a48829cf0807fdcd1c0f89230afab358cc67/docker/docker_VARS#L10
