### ISSUE TITLE
Inputs are not correctly identified  in R 

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#681]
Inputs are not correctly identified  in R. If we have a data frame: 
```
df.datain=read.csv(param_datain,stringsAsFactors=F,sep = ";", dec = ".")
```
And try to modify a column: 
```
df.datain$measurementremarks <- tolower(df.datain$measurementremarks) # eliminate capital letters
```

The containerizer treats it as an input variable:
![Screenshot from 2023-06-13 13-26-45](https://github.com/QCDIS/NaaVRE/assets/9680609/5599b68a-f2cc-4858-a7f1-ac7ddf69f7fe)

As a workaround, we should declare the variable in the same cell before using it:
```
# read input cvs
df.datain=read.csv(param_datain,stringsAsFactors=F,sep = ";", dec = ".")
measurementremarks = tolower(df.datain$measurementremarks) # eliminate capital letters
df.datain$measurementremarks <- tolower(df.datain$measurementremarks) # eliminate capital letters
```

**Comment by DiederikBlanson** [comment]
@skoulouzis this could be solved by doing:
`
df.datain["measurementremarks"]`

instead of:

`df.datain$measurementremarks`

We could go two ways here:
1. Inform that the user needs to write code like ["measurementremarks"], but this might not be ideal to do?
2. We do a replace on $VARIABLE_NAME to ["VARIABLE_NAME"], what is your opinion on this?
